name: mc-installer
title: Minecraft Installer
version: "5.3"
summary: A simple installer for Minecraft - Java Edition
description: | 
  A simple installer for Minecraft - Java Edition. 
license: MIT

base: core18
grade: stable
confinement: strict

apps:
  mc-installer:
    command: desktop-launch $SNAP/launch
    plugs:
      - x11
      - network
      - unity7
      - opengl
      - pulseaudio
      - wayland
      - desktop
      - desktop-legacy
      - browser-support
      - home
    environment:
      PYTHONPATH: $SNAP/gnome-platform/usr/lib/python3/dist-packages

parts:
  launcher:
    plugin: dump
    source: scripts
    after: [desktop-gnome-platform]

  game:
    plugin: nil
    # Fix for "package contains external symlinks" issue
    # https://forum.snapcraft.io/t/resolve-package-contains-external-symlinks-error-when-trying-to-snap/2963
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-8-jre-headless        
    stage-packages:
      - libgl1-mesa-dri
      - libswt-gtk-3-java
      - x11-xserver-utils
      - python3-requests
      - openjdk-8-jre-headless
      - libxss1
      - libgconf2-4
      - libcurl3

  # This part installs the `desktop-launch` script which initialises desktop
  # features such as fonts, themes and the XDG environment.
  #
  # It is copied straight from the snapcraft desktop helpers project. Please
  # periodically check the source for updates and copy the changes.
  #    https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  #
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - gcc
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

plugs:
  # GTK libraries
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  # Common GTK themes
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
