name: mc-installer
title: Minecraft Installer
version: '9.1'
summary: A simple installer for Minecraft - Java Edition
description: | 
  A simple installer for Minecraft - Java Edition.
license: MIT

assumes:
  - command-chain
  
base: core20
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64

plugs:
  dot-minecraft:
    interface: personal-files
    write:
      - $HOME/.minecraft

apps:
  mc-installer:
    extensions:
      - gnome-3-38
    command: bin/launch
    command-chain: 
      - bin/homeishome-launch    
    plugs:
      - network
      - opengl
      - audio-playback
      - pulseaudio
      - browser-support
      - home
      - dot-minecraft      
    environment:
      PYTHONPATH: $SNAP_DESKTOP_RUNTIME/usr/lib/python3.6/site-packages
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64/

parts:
  launcher:
    plugin: dump
    source: scripts

  game:
    plugin: nil
    build-packages:
      - openjdk-8-jre-headless        
      - ca-certificates-java
    stage-packages:
      - libglu1-mesa
      - libswt-gtk-3-java
      - python3-requests
      - openjdk-8-jre-headless
      - libxss1
      - libgconf-2-4
      - libcurl4
  
  cleanup:
    after: 
      - game
      - launcher
    plugin: nil
    build-snaps: 
      - core20
      - gnome-3-38-2004
    override-prime: |
      set -eux
      for snap in "core20" "gnome-3-38"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
