name: mc-installer
version: 3.3
summary: Minecraft Downloader and Installer
description: |
    Minecraft installer for Linux distributions. Downloads and installs Minecraft and keeps your version up-to-date.  
grade: stable
confinement: strict

apps:
  mc-installer:
    command: desktop-launch $SNAP/launch
    plugs:
      - x11
      - network
      - unity7
      - opengl
      - pulseaudio
      - wayland
      - desktop
      - desktop-legacy
      - browser-support
      - home

parts:
  launcher:
    plugin: dump
    source: scripts
    after: [desktop-qt5]

  game:
    plugin: nil
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-8-jre-headless
    stage-packages:
      - libgl1-mesa-dri
      - libpulse0
      - yad
      - wget
      - libxext6
      - libxrender1
      - libxtst6
      - libxi6
      - libswt-gtk-3-java
      - libwebkit2gtk-3.0-25
      - x11-xserver-utils
      - python3-gi
      - python3-gi-cairo
      - python3-cairo
      - gir1.2-gtk-3.0
      - openjdk-8-jre-headless
      - libxss1
      - libgconf2-4
      - libasound2
      - libcurl3
