---

name: minecraft-nsg
version: git
summary: Minecraft Launcher downloader
description: |
    This snap will download Oracle Java and Minecraft Launcher to
    your computer. The applications are NOT distributed in this
    snap.
grade: stable
confinement: strict

apps:
  minecraft-nsg:
    command: desktop-launch $SNAP/launch
    plugs:
      - x11
      - network
      - unity7
      - opengl
      - pulseaudio

parts:
  launcher:
    plugin: dump
    source: scripts
    after: [desktop-gtk3]
  desktop-gtk3:
    stage:
      - -usr/sbin/update-icon-caches
  game:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      - libpulse0
      - yad
      - wget

      # Install needed deps
      - libxext6
      - libxrender1
      - libxtst6
      - libxi6
      - libswt-gtk-3-java
      - libwebkit2gtk-3.0-25

      # lwjgl uses the COMMAND xrandr !?!?
      - x11-xserver-utils

      # For the downloader
      - python3-gi
      - python3-gi-cairo
      - python3-cairo
      - gir1.2-gtk-3.0

      # The launcher do not work with modern java, so
      # I will give openjdk a try! If this works it's
      # nicer because I can distribute it with the snap.
      - openjdk-8-jre-headless
      - ca-certificates-java
